
name: Build Supermark Site
on: [push]
jobs:
  Build-Supermark:
    runs-on: ubuntu-latest
    steps:
      - name: Pip Installer
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            supermark
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pandoc
        run: |
          $CONDA/bin/conda install pandoc
          ln -s $CONDA/bin/pandoc /usr/local/bin/pandoc
      - name: Run Supermark
        run: |
          supermark build --all --log
      - name: Push
        uses: actions-x/commit@v6
